# Problem 2
# Even Fib Nums

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

limit = 4000000
arr = [1, 2]
newArr = []
arrSum = 0

while arrSum < limit:
    index = len(arr)
    arrSum = arr[index - 1] + arr[index - 2]
    arr.append(arrSum)

for i in range(0, len(arr)):
    if arr[i] % 2 == 0:
        newArr.append(arr[i])

print(sum(newArr))